vendor: Inspur
name: AIStation
version: v2.1
website_url: https://www.inspur.com/lcjtww/2526894/2526897/2563322/2563340/index.html
documentation_url: https://www.inspur.com/lcjtww/resource/cms/2022/03/2022033015163951298.pdf
product_logo_url: https://github.com/Iamlovingit/k8s-conformance/blob/master/v1.23/aistation/AIStation_logo.ai
type: hosted platform 
description: AIStation inference platform is a one-stop AI reasoning service platform developed by Inspur，it faces enterprise AI application deployment and online service management scenarios. 
